[workspace]
authors = ["sophia <scastellarin@quansight.com>"]
channels = ["conda-forge"]
name = "test-abc"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
flask = ">=3.1.2,<4"
beautifulsoup4 = ">=4.14.2,<5"
